trigger:
- staging

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: Pipeline de Integração Contínua
  jobs:
    - job: Pipeline CI
      displayName: Execução da Pipeline CI
      steps:
      - script: |
          node --version