trigger:
- staging

pool:
  vmImage: ubuntu-latest

variables:
  - name: DOCKER_REPOSITORY
    value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)

stages:
- stage: CI
  displayName: Pipeline de Integração Contínua
  jobs:
    - job: Pipeline_CI
      displayName: Execução da Pipeline CI
      steps:
      - task: NodeTool@0
        displayName: Intalação da versão correta do NodeJs
        inputs:
          versionSpec: '14.19.3'
    
    - job: Publish
      displayName: Construção e Publicação
      dependsOn: Pipeline_CI
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Thandi13_Docker_Connection'
          repository: 'thandi13/simple-chat'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            v-ADO-$(Build.BuildId)
            latest
- stage: CD
  displayName: Pipeline de Deploy Contínuo
  dependsOn: CI
  jobs: 
  - job: Deploy
    displayName: Deploy na instância 
    steps:

      - script: |
          echo $(DOCKER_REPOSITORY) 
