trigger:
- staging

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: Pipeline de Integração Contínua
  jobs:
    - job: Pipeline_CI
      displayName: Execução da Pipeline CI
      steps:
      - task: NodeTool@0
        displayName: Intalação da versão correta do NodeJs
        inputs:
          versionSpec: '14.19.3'
      - task: Docker@2
        inputs:
          containerRegistry: 'Thandi13_Docker_Connection'
          repository: 'thandi13/simple-chat'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            $(Build.BuildId)
            latest