version: '3'

networks:
  api-network:
    driver: bridge 

volumes:
  mongo-vol:

services:
  mongo:
    image: mongo:5.0
    volumes:
      - "mongo-vol:/data/db"
    networks:
      - "api-network"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser 
      MONGO_INITDB_ROOT_PASSWORD: mongopwd   
    #ports:
      #- 27017:27017

  simple-chat:
    image: thandi13/simple-chat:v0.93
    build: 
      dockerfile: Dockerfile
    environment: 
      MONGODB_URI: mongodb://mongouser:mongopwd@mongo:27017/admin 
    networks:
      - "api-network"
    ports:
      - 3000:3000
    depends_on:
      - "mongodb"
  
