apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tag: v0.95
  template:
    metadata:
      labels:
        tag: v0.95
    spec:
      containers:
      - name: simple-chat-web-app
        image: thandi13/simple-chat:v0.95
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-chat-service
spec:
  selector:
    tag: v0.95
  ports:
  - protocol: TCP
    port: 3000 
    nodePort: 30000
  type: NodePort 
        