mongo:
  name: mainstreet
  tag: 5.0
  portNumber: 131313 
  credentials:
    userName: flavio 
    userPassword: 131313 
deploy:
  replicaQuantity: 1
app:
  tag: v0.95
  mongoUri: mongodb://flavio:131313@mainstreet:131313/admin 
  serverPort: 131313
  loadbalancer:
    type: 
      enabled: true