# The Simple-Chat Web Application Service 
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:  
  - port: 80
    targetPort: 3000 
    nodePort: 30000
  type: NodePort 
        