# The Simple-Chat Web Application Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: thandi13/simple-chat:v0.95
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: mongodb://mongouser:mongopwd@mongo:27017/admin 
        - name: PORT
          value: "3000"
---
# The Simple-Chat Web Application Service 
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:  
  - port: 80
    targetPort: 3000 
    nodePort: 30000
  type: NodePort 
        