# The MongoDB Deployment 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:{{ .Values.mongo.tag }}
        ports:
          -  containerPort: {{ .Values.mongo.portNumber }} 
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.mongo.credentials.userName }}  
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.mongo.credentials.userPassword }}  
