# The MongoDB Service 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
spec:
  selector:
    app: {{ .Release.Name }}-mongo-service
  ports:
  - port: 27017 
  type: ClusterIP 