# The MongoDB Deployment 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb-deployment
    spec:
      containers:
      - name: mongo
        image: mongo:{{ .Values.mongo.tag }}
        ports:
          -  containerPort: {{ .Values.mongo.numberPort }} 
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.mongo.credentials.userName }}  
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.mongo.credentials.userPassword }}  
