# The MongoDB Deployment 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.mongo.name | default "mongo" }}
spec:
  replicas: {{ .Values.deploy.replicaQuantity | default 1 }} 
  selector:
    matchLabels:
      app: {{ .Values.mongo.name | default "mongo" }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.name | default "mongo" }}
    spec:
      containers:
      - name: {{ .Values.mongo.name | default "mongo" }}
        image: mongo:{{ .Values.mongo.tag | default 5.0 }}
        ports:
          -  containerPort: {{ .Values.mongo.portNumber | default 27017 }} 
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-simple-chat-app-secret 
              key: mongo-username  
        - name: MONGO_INITDB_ROOT_PASSWORD 
          value: {{ .Values.mongo.credentials.userPassword }}
        #- name: MONGO_INITDB_ROOT_PASSWORD
          #valueFrom:
            #secretKeyRef:
              #key:  userPassword
              #name: {{ .Release.Name }}-simple-chat-app-secret

