apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-simple-chat-app-secret
data:
    name: {{ .Values.mongo.name }}
    userName: {{ .Values.mongo.credentials.userName | b64enc }} 
    userPassword: {{ .Values.mongo.credentials.userPassword | b64enc }} 
    mongoUri: {{ .Values.app.mongoUri | b64enc }}
    serverPort: {{ .Values.app.serverPort }}
