apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-simple-chat-app-secret
data:
    userName: {{ .Values.mongo.credentials.userName }}                
    serverPort: "{{ .Values.app.serverPort }}"
