apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-simple-chat-app-secret
type: Opaque
data:
  userName: {{ .Values.mongo.credentials.userName | b64enc | quote }}
  userPassword: {{ .Values.mongo.credentials.userPassword | b64enc | quote }}
  mongoUri: {{ .Values.app.mongoUri | b64enc | quote }}
  serverPort: "{{ .Values.app.serverPort }}"