apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-simple-chat-app-secret
type: Opaque
data:
    mongo-username: {{ .Values.mongo.credentials.userName | b64enc | quote }}                
    serverPort: "{{ .Values.app.serverPort }}"
